### ISSUE TITLE
ナワバリバトルのデータに対してガチマッチ用のデータを送ると内部エラーが発生する

### ISSUE THREAD

**Issue by kakunpc** [fetus-hina/stat.ink#227]
[https://stat.ink/@kakunpc/spl2/4850](https://stat.ink/@kakunpc/spl2/4850)

ガチマッチ用のデータ「my_team_count」と「his_team_count」をナワバリバトルのモードのものに対して値を入れていまうと内部エラーとなっていまいます。

**Comment by fetus-hina** [comment]
両チームのカウントが 0 の時、0 除算が発生
```
yii\base\ErrorException: Division by zero in /home/statink/stat.ink/views/show-v2/_battle_details.php:228
Stack trace:
#0 /home/statink/stat.ink/views/show-v2/_battle_details.php(228): yii\base\ErrorHandler->handleError(2, 'Division by zer...', '/home/statink/s...', 228, Array)
#1 [internal function]: yii\base\View->{closure}(Object(app\models\Battle2), Object(yii\widgets\DetailView))
#2 /home/statink/stat.ink/vendor/yiisoft/yii2/widgets/DetailView.php(243): call_user_func(Object(Closure), Object(app\models\Battle2), Object(yii\widgets\DetailView))
#3 /home/statink/stat.ink/vendor/yiisoft/yii2/widgets/DetailView.php(141): yii\widgets\DetailView->normalizeAttributes()
#4 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Object.php(107): yii\widgets\DetailView->init()
#5 [internal function]: yii\base\Object->__construct(Array)
#6 /home/statink/stat.ink/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#7 /home/statink/stat.ink/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\widgets\\Det...', Array, Array)
#8 /home/statink/stat.ink/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\widgets\\Det...', Array, Array)
#9 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Widget.php(136): yii\BaseYii::createObject(Array)
#10 /home/statink/stat.ink/views/show-v2/_battle_details.php(516): yii\base\Widget::widget(Array)
#11 /home/statink/stat.ink/vendor/yiisoft/yii2/base/View.php(330): require('/home/statink/s...')
#12 /home/statink/stat.ink/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/statink/s...', Array)
#13 /home/statink/stat.ink/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/statink/s...', Array, NULL)
#14 /home/statink/stat.ink/views/show-v2/battle.php(164): yii\base\View->render('_battle_details', Array)
#15 /home/statink/stat.ink/vendor/yiisoft/yii2/base/View.php(330): require('/home/statink/s...')
#16 /home/statink/stat.ink/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/statink/s...', Array)
#17 /home/statink/stat.ink/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/statink/s...', Array, Object(app\controllers\ShowV2Controller))
#18 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Controller.php(381): yii\base\View->render('battle', Array, Object(app\controllers\ShowV2Controller))
#19 /home/statink/stat.ink/actions/show/v2/BattleAction.php(37): yii\base\Controller->render('battle', Array)
#20 [internal function]: app\actions\show\v2\BattleAction->run()
#21 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#22 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array)
#23 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('battle', Array)
#24 /home/statink/stat.ink/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('show-v2/battle', Array)
#25 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(app\components\web\Request))
#26 /home/statink/stat.ink/web/index.php(20): yii\base\Application->run()
#27 {main}
```

**Comment by fetus-hina** [comment]
修正しましたが、できれば不要なデータは送信しないようにお願いします。
（そもそも受け付けること自体がバグとも言える）

**Comment by kakunpc** [comment]
すみません
次送る時から不要なデータは防ぐようにしておきます。
対応ありがとうございました。
