### ISSUE TITLE
[2] Can't delete a battle when players' data registered

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#262]
Reported: @dofine https://github.com/fetus-hina/stat.ink/issues/245#issuecomment-323507063

```
2017-08-19 16:40:09 [IPADDR][USERID][-][error][yii\db\IntegrityException] PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "battle2" violates foreign key constraint "battle_player2_battle_id_fkey" on table "battle_player2"
DETAIL:  Key (id)=(17313) is still referenced from table "battle_player2". in /home/statink/stat.ink/vendor/yiisoft/yii2/db/Command.php:842
Stack trace:
#0 /home/statink/stat.ink/vendor/yiisoft/yii2/db/Command.php(842): PDOStatement->execute()
#1 /home/statink/stat.ink/vendor/yiisoft/yii2/db/ActiveRecord.php(296): yii\db\Command->execute()
#2 /home/statink/stat.ink/vendor/yiisoft/yii2/db/ActiveRecord.php(653): yii\db\ActiveRecord::deleteAll(Array)
#3 /home/statink/stat.ink/vendor/yiisoft/yii2/db/ActiveRecord.php(613): yii\db\ActiveRecord->deleteInternal()
#4 /home/statink/stat.ink/models/Battle2DeleteForm.php(52): yii\db\ActiveRecord->delete()
#5 /home/statink/stat.ink/actions/show/v2/EditBattleAction.php(58): app\models\Battle2DeleteForm->delete()
#6 [internal function]: app\actions\show\v2\EditBattleAction->run()
#7 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#8 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array)
#9 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('edit-battle', Array)
#10 /home/statink/stat.ink/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('show-v2/edit-ba...', Array)
#11 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(app\components\web\Request))
#12 /home/statink/stat.ink/web/index.php(20): yii\base\Application->run()
#13 {main}
```

**Comment by fetus-hina** [comment]
The issue that you reported probably fixed in commit 14b3cef44abd213b2ffc9812adda8cfe4ab8556e.
@dofine Could you try it again and report fixed it or not?

**Comment by dofine** [comment]
@fetus-hina Hi, it's all working now. Thanks for your quick fix!

**Comment by fetus-hina** [comment]
@dofine Thank you for the report and checking!
