### ISSUE TITLE
最近どうもDockerビルドが壊れたらしい

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#76]
まだ詳細は見てない

**Comment by fetus-hina** [comment]
```
*** applying m160122_062721_propeller
Exception: Getting unknown property: app\models\DeathReason::weapon_id (/home/statink/stat.ink/vendor/yiisoft/yii2/base/Component.php:143)
#0 /home/statink/stat.ink/vendor/yiisoft/yii2/db/BaseActiveRecord.php(247): yii\base\Component->__get('weapon_id')
#1 /home/statink/stat.ink/vendor/yiisoft/yii2/validators/Validator.php(240): yii\db\BaseActiveRecord->__get('weapon_id')
#2 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Model.php(356): yii\validators\Validator->validateAttributes(Object(app\models\DeathReason), Array)
#3 /home/statink/stat.ink/vendor/yiisoft/yii2/db/ActiveRecord.php(421): yii\base\Model->validate(Array)
#4 /home/statink/stat.ink/vendor/yiisoft/yii2/db/BaseActiveRecord.php(593): yii\db\ActiveRecord->insert(true, NULL)
#5 /home/statink/stat.ink/migrations/m160122_062721_propeller.php(27): yii\db\BaseActiveRecord->save()
#6 /home/statink/stat.ink/vendor/yiisoft/yii2/db/Migration.php(93): m160122_062721_propeller->safeUp()
#7 /home/statink/stat.ink/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(562): yii\db\Migration->up()
#8 /home/statink/stat.ink/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(151): yii\console\controllers\BaseMigrateController->migrateUp('m160122_062721_...')
#9 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#10 /home/statink/stat.ink/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#11 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#12 /home/statink/stat.ink/vendor/yiisoft/yii2/console/Controller.php(108): yii\base\Controller->runAction('up', Array)
#13 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('up', Array)
#14 /home/statink/stat.ink/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('migrate/up', Array)
#15 /home/statink/stat.ink/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate/up', Array)
#16 /home/statink/stat.ink/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#17 /home/statink/stat.ink/yii(23): yii\base\Application->run()
#18 {main}
*** failed to apply m160122_062721_propeller (time: 0.021s)
```
